### ISSUE TITLE
How to send push notifications to devices identified by app center identifiers?

### ISSUE THREAD

**Issue by thisisthekap** [Azure/AzureNotificationHubs#7]
How to migrate existing customers? Specifically: How to send a push notification to specific device which is identified by its app center installation id without app center push?

**Comment by merzink** [comment]
Hi @thisisthekap - When you migrate your application off App Center Push, you'll switch to using the Azure Notification Hubs (ANH) SDK, which will register those devices in your new notification hub and be available for targeting. Check out the additional resources on [registration management and targeting](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-registration-management).

**Comment by thisisthekap** [comment]
Using this way, the device will have to reregister until it is targetable. Is it possible to target a device using the Azure Notification Hub without reregistration, but by using the registration that way already performed using app center?

**Comment by merzink** [comment]
@thisisthekap - Yes, the devices would be re-registered in your own hub within Azure Notification Hubs (ANH). Once App Center Push (ACP) goes offline, that system won't be available so devices running your older app (which would be using the ACP SDK) won't be registered with ACP anymore and cannot be targeted using ANH. Once you switch your app to using the ANH SDK, any device running your app will be registered in your new hub. Note that ACP will remain available until December 31, 2020 so you do have time to make the switch.

There is a separate notion of 'tags' in ANH and you can check out how to [incorporate tags](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-tags-segment-push-message) for notification targeting as well.

**Comment by thisisthekap** [comment]
@merzink So if I got you right, there basically is no way to migrate existing devices. We simply have to add ANH as separate way of sending push notifications. "Old" devices can be reached via AppCenter Push until the end of this year.

Is this the way to go?

**Comment by tjsomasundaram-zz** [comment]
@thisisthekap yes, the suggested method is to add ANH as a way to send notifications and reach "old" devices via App Center Push until they are registered with ANH.
