### ISSUE TITLE
NotificationHubsSampleAndroid: File ..\externals\notificationhubs.aar does not exist and file creation wasn't requested    at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options) in /Users/runner/runners/2.165.0/work/1/s/ZipArchive.cs:line 273    at Xamarin.Android.Tasks.CreateLibraryResourceArchive.RunTask()    at Xamarin.Android.Tasks.AndroidTask.Execute()	Xamarin.Azure.NotificationHubs.Android	E:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets	431	

### ISSUE THREAD

**Issue by donaldashworth** [Azure/AzureNotificationHubs#9]
https://github.com/xamarin/XamarinComponents/tree/master/XPlat/AzureMessaging/Android/samples is missing ..\externals\notificationhubs.aar.

I cannot find anything describing how/where to obtain or setup externals. 

I am hoping to get the newest/supported Notfication Hub Samples up and running before applying these changes to our custom mobile app.

**Comment by mpodwysocki** [comment]
@donaldashworth I see you're referring to the source project, `Xamarin.Azure.NotificationHubs.Android.csproj`.  If you want to build that directly versus using the NuGet package, you will need to run the cake build for our [build.cake](https://github.com/xamarin/XamarinComponents/blob/master/XPlat/AzureMessaging/build.cake), which can be done by installing [cake](https://cakebuild.net/) and then running the following:
```
cake build
```

This will download the externals for both iOS and Android and then you can compile those directly.

**Comment by marstr** [comment]
@mpodwysocki is correct. The `.aar` is not missing. You can find the existing documentation on how to build the repository here:

https://github.com/xamarin/XamarinComponents#building
